<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ankur" failures="0" tests="6" name="Test" time="46.471" errors="0" timestamp="2024-01-02T12:30:30 IST">
  <testcase classname="Register.DWS_Register_02_Test" name="Register_user" time="3.044"/>
  <testcase classname="login.DWS_Login_01_Test" name="Login_to_application_with_valid_credentials" time="1.115"/>
  <testcase classname="login.DWS_Login_01_Test" name="Login_to_application_with_valid_credentials" time="1.525"/>
  <testcase classname="login.DWS_Login_01_Test" name="Login_to_application_with_valid_credentials" time="1.388"/>
  <testcase classname="login.DWS_Login_01_Test" name="Login_to_application_with_valid_credentials" time="0.85"/>
  <testcase classname="DisplayErrorMsg.DWS_VerifyErrorMsg_08_Test" name="Verify_the_error_message" time="6.391"/>
</testsuite> <!-- Test -->
